title: "Marco Rando"
description: "Academic website of Marco Rando"
url: "https://marcorando.github.io"

author:
  name: "Marco Rando"
  email: "marco.rando0396@gmail.com"
  affiliation: "Université Côte d'Azur, Inria, CNRS, LJAD"

markdown: kramdown
theme: null
plugins: []
